cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

script: 
- sbt ++$TRAVIS_SCALA_VERSION compile test:compile

scala:
  - 2.12.2

jdk:
  - oraclejdk8
  - openjdk8


notifications:
  email:vinay.bhagwat@afourtech.com