cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

script: 
- sbt ++$TRAVIS_SCALA_VERSION compile test:compile

scala:
  - 2.12.2

jdk:
  - oraclejdk8
  - openjdk8


deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "scala-travis-bucket"
notifications:
  email:vinay.bhagwat@afourtech.com